CREATE TABLE NOTIFICATION
(
	ID BIGINT AUTO_INCREMENT PRIMARY KEY ,
	NOTIFIER BIGINT NOT NULL,
	RECEIVER BIGINT NOT NULL,
	OUTERID BIGINT NOT NULL,
	TYPE INT NOT NULL,
	GMT_CREATE BIGINT NOT NULL,
	STATUS INT DEFAULT 0 NOT NULL,
);

COMMENT ON COLUMN NOTIFICATION.NOTIFIER IS '发送通知的用户';

COMMENT ON COLUMN NOTIFICATION.RECEIVER IS '接收消息用户';

COMMENT ON COLUMN NOTIFICATION.OUTERID IS '外键ID';

COMMENT ON COLUMN NOTIFICATION.TYPE IS '类型';

COMMENT ON COLUMN NOTIFICATION.STATUS IS '未读数';

